### ISSUE TITLE
404 on DS and RM

### ISSUE THREAD

**Issue by dwillmore** [openwch/ch32v002_004_005_006_007#2]
The links from the datasheet README.md to the RM and DS are 404 at the WCH site.

**Comment by dwillmore** [comment]
https://www.wch-ic.com/downloads/CH32V00XRM_PDF.html
https://www.wch-ic.com/downloads/CH32V006DS0_PDF.html
both 404 from https://github.com/openwch/ch32v002_004_005_006_007/blob/main/Datasheet/README.md

**Comment by dwillmore** [comment]
The 006DS link now works for the Chinese and English versions of the page.

Could the other chips be added to that page as well?  002, 004, and 007?

The English 002DS is: https://www.wch-ic.com/downloads/CH32V002DS0_PDF.htm 
The Chinese 002DS is: https://www.wch.cn/downloads/CH32V002DS0_PDF.html

**Comment by dwillmore** [comment]
The English 004DS is: https://www.wch-ic.com/downloads/CH32V004DS0_PDF.html
The Chinese 004DS is: https://www.wch.cn/downloads/CH32V004DS0_PDF.html

**Comment by dwillmore** [comment]
All that is missing is the 007/M007 in both languages (it had been released, but disappeared) and the reference manual in English.

**Comment by DingZhongGang** [comment]
Thank you for your reminder. The latest datasheet document has added all existing DS document links. Unfortunately, the 007 series documents have not been updated yet. We will update and upload them to the official website as soon as possible.

**Comment by dwillmore** [comment]
That's wonderful, thank you.  I'll close the issue for now.
